SELECT ROWNUM orders,a.* FROM
(SELECT
	COUNT(TS_LOG_VISIT.F_FOOTPRINT_ID) count,
	TB_USER.F_USER_NAME name,
	TB_USER.F_URL_PATH pic
FROM
	TS_LOG_VISIT
	LEFT JOIN TB_USER ON TB_USER.F_USER_ID = TS_LOG_VISIT.F_USER_ID
GROUP BY
	TB_USER.F_USER_NAME,
	TB_USER.F_URL_PATH
ORDER BY count DESC) a WHERE ROWNUM BETWEEN 1 AND 10