SELECT ROWNUM orders,a.* FROM
(SELECT
	COUNT(TS_LOG_VISIT.F_FOOTPRINT_ID) count,
	TB_FOOTPRINT.F_NAME name
FROM
	TS_LOG_VISIT
	LEFT JOIN TB_FOOTPRINT ON TB_FOOTPRINT.F_ID = TS_LOG_VISIT.F_FOOTPRINT_ID
WHERE
	to_char(sysdate,'yyyy-mm')=to_char(TS_LOG_VISIT.F_RECORD_TIME,'yyyy-mm')
GROUP BY
	TB_FOOTPRINT.F_NAME
ORDER BY count DESC) a WHERE ROWNUM BETWEEN 1 AND 10;