SELECT ROWNUM orders,a.* FROM
(SELECT
	SUM( TB_INTEGRAL.F_INTEGRAL ) count,
	TB_USER.F_NICKNAME name,
	TB_USER.F_URL_PATH pic
FROM
	TB_INTEGRAL
	LEFT JOIN TB_USER ON TB_INTEGRAL.F_USER_ID = TB_USER.F_USER_ID 
WHERE
	to_char(sysdate,'yyyy-mm')=substr(TB_INTEGRAL.F_RECODE_TIME,1,7)
GROUP BY
	TB_USER.F_USER_ID,
	TB_USER.F_NICKNAME,
	TB_USER.F_URL_PATH
ORDER BY count DESC) a  WHERE ROWNUM BETWEEN 1 AND 10